FROM python:3.11

RUN pip install pandas

RUN pip install numpy

RUN pip install scikit-learn

RUN pip install geopy

RUN pip install sqlalchemy psycopg2

WORKDIR /app

ENTRYPOINT ["python","src/main.py"]






