version: "3.9"


services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=green_taxis
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./m2_queries:/var/lib/m2_queries
    ports:
      - "5432:5432"
  ingest_database:
    build: .
    image: cleandata
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
    depends_on:
      - pgdatabase
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com  # Set the default email for pgAdmin
      - PGADMIN_DEFAULT_PASSWORD=root            # Set the default password for pgAdmin
    ports:
      - "5050:80"                                # Map port 5050 on the host to port 80 on the container
    depends_on:
      - pgdatabase

volumes:
 postgres-data:
