services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=green_taxisM4
    volumes:
      - "green_tripdata_2016-01:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"    
    networks:
      - airflow
volumes:
 green_tripdata_2016-01:
networks:
  airflow:
    external:
      name: airflow_milestone4_default  
